#!/usr/bin/env bash
# 🚀 Quick Start: Deploy Vercel em 4 Passos
# Execute este script ou siga os comandos manualmente

echo "================================"
echo "🚀 VERCEL DEPLOY - QUICK START"
echo "================================"
echo ""

# PASSO 1: Testar Localmente
echo "📝 PASSO 1: Testando localmente..."
echo "  Abra dois terminais:"
echo ""
echo "  Terminal 1 (Back-end):"
echo "    cd server"
echo "    npm install"
echo "    npm run dev"
echo ""
echo "  Terminal 2 (Front-end):"
echo "    cd client"
echo "    npm install"
echo "    npm run dev"
echo ""
echo "  ✓ Abra http://localhost:5173"
echo "  ✓ Teste se está funcionando"
echo ""
read -p "Pressione ENTER quando tudo estiver funcionando..."

# PASSO 2: GitHub
echo ""
echo "================================"
echo "🐙 PASSO 2: Criando repositório GitHub..."
echo "================================"
echo ""
echo "1. Abra https://github.com/new"
echo "2. Crie um repositório chamado: papodelivro"
echo ""
echo "Depois, copie e execute:"
echo ""
echo "  git remote add origin https://github.com/SEU-USUARIO/papodelivro.git"
echo "  git add ."
echo "  git commit -m 'chore: preparar para deploy vercel'"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
read -p "Pressione ENTER quando terminar..."

# PASSO 3: Vercel Back-End
echo ""
echo "================================"
echo "🔙 PASSO 3: Deploy Back-End"
echo "================================"
echo ""
echo "1. Abra https://vercel.com/dashboard"
echo "2. New Project"
echo "3. Conecte seu repositório GitHub (papodelivro)"
echo "4. Configuração:"
echo "   - Root Directory: server"
echo "   - Framework: Other (Node.js)"
echo "   - Build: npm run build"
echo "   - Output: dist"
echo ""
echo "5. Environment Variables (adicione uma por uma):"
echo "   DATABASE_URL=postgresql://..."
echo "   JWT_SECRET=sua-chave-secreta"
echo "   SUPABASE_URL=https://seu-projeto.supabase.co"
echo "   SUPABASE_KEY=sua-chave"
echo "   NODE_ENV=production"
echo ""
echo "6. Deploy"
echo ""
echo "✓ Copie a URL da API: https://seu-backend-name.vercel.app"
echo ""
read -p "Pressione ENTER quando terminar..."

# PASSO 4: Vercel Front-End
echo ""
echo "================================"
echo "🎨 PASSO 4: Deploy Front-End"
echo "================================"
echo ""
echo "1. Volte a https://vercel.com/dashboard"
echo "2. New Project"
echo "3. Selecione MESMO repositório"
echo "4. Configuração:"
echo "   - Root Directory: client"
echo "   - Framework: Vite"
echo "   - Build: npm run build"
echo "   - Output: dist"
echo ""
echo "5. Environment Variables:"
echo "   VITE_API_URL=https://seu-backend-name.vercel.app/api"
echo "   VITE_SUPABASE_URL=https://seu-projeto.supabase.co"
echo "   VITE_SUPABASE_KEY=sua-chave-publica"
echo "   VITE_MODE=production"
echo ""
echo "6. Deploy"
echo ""
echo "✓ Copie a URL do Front: https://seu-frontend-name.vercel.app"
echo ""
read -p "Pressione ENTER quando terminar..."

# PASSO 5: Reconfigurar CORS
echo ""
echo "================================"
echo "🔒 PASSO 5: Reconfigurar CORS"
echo "================================"
echo ""
echo "1. Volte ao projeto Back-End na Vercel"
echo "2. Settings → Environment Variables"
echo "3. Adicione/Atualize:"
echo "   FRONTEND_URL=https://seu-frontend-name.vercel.app"
echo "   ALLOWED_ORIGINS=https://seu-frontend-name.vercel.app"
echo ""
echo "✓ Vercel fará deploy automático"
echo ""
read -p "Pressione ENTER quando terminar..."

# PASSO 6: Validar
echo ""
echo "================================"
echo "✅ PASSO 6: Testando"
echo "================================"
echo ""
echo "No navegador (DevTools - Console):"
echo ""
echo "1. Abra seu front-end em produção"
echo ""
echo "2. Execute no console:"
echo ""
cat << 'EOF'
// Testar API
fetch('https://seu-backend-name.vercel.app/health-check')
  .then(r => r.json())
  .then(d => console.log('✅ API OK:', d))
  .catch(e => console.error('❌ Erro:', e));

// Testar CORS
fetch('https://seu-backend-name.vercel.app/api/books')
  .then(r => console.log('✅ Status:', r.status))
  .catch(e => console.error('❌ CORS Error:', e));
EOF
echo ""
echo ""

# FIM
echo "================================"
echo "🎉 DEPLOYMENT COMPLETO!"
echo "================================"
echo ""
echo "URLs de Produção:"
echo "  Front-end: https://seu-frontend-name.vercel.app"
echo "  Back-end:  https://seu-backend-name.vercel.app"
echo ""
echo "Daqui em diante, qualquer 'git push' faz deploy automático! 🚀"
echo ""
echo "Próximos passos:"
echo "  • Configurar domínio personalizado (opcional)"
echo "  • Ativar monitoramento (Vercel Analytics)"
echo "  • Configurar CI/CD com testes"
echo ""
echo "Documentação disponível em:"
echo "  • README_DEPLOY.md - Guia completo"
echo "  • DEPLOYMENT_FLOW.md - Fluxo visual"
echo "  • DEPLOY_REFERENCE.md - Referência rápida"
echo ""
